### ISSUE TITLE
How to enable the minification step?

### ISSUE THREAD

**Issue by IjzerenHein** [vesselsoft/metro-minify-obfuscator#2]
Hi! Thanks for this repo, it looks like exactly what I was looking for. ❤️ 

I just have one question, how do you activate the minification step, cause by default it doesn't appear to do anything.

@muhamad-rizki

**Comment by byrizki** [comment]
Hi @IjzerenHein 
this library minified your bundle on minification process, this will produce minified + obfuscated bundle, you can see the difference when you enable minification on dev menu

**Comment by IjzerenHein** [comment]
Alright thank you @muhamad-rizki

**Comment by byrizki** [comment]
I'll close the issue then, thanks
